name: MMKP-solver
channels:
  - gurobi
  - https://conda.anaconda.org/gurobi
  - defaults
  - conda-forge
dependencies:
  - gurobi=10.0.1
  - matplotlib=3.5.2
  - pandas=1.4.3
  - pydantic=1.9.0
  - python=3.10.6
  - scipy=1.10.1